config/routes.rb
Rails.application.routes.draw do
  resources :cities

  get 'reports/index'

  get 'reports/sumbycustomer'

  get 'reports/sumbytime'

  get 'reports/sumbycity'

  devise_for :users
  resources :colours

  resources :order_lines do
    get 'additem', to: "orders#add_order_lines"
  end

  resources :orders do
    get 'compute', to: "orders#compute"
  end

  resources :customers

  resources :products

  root 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :city
  has_many :orders
  validates :owner, :store, :phone, presence: true
  before_save { |customer| customer.owner = customer.owner.downcase }
  before_save { |customer| customer.store = customer.store.downcase }
  
  def self.search(search)
    where("store like lower(?)", "%#{search}%")
  end
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    if params[:search]
      @customers = Customer.search(params[:search])
    else
      @customers = Customer.all
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @orders = @customer.orders
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  # def destroy
  #   @customer.destroy
  #   respond_to do |format|
  #     format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:owner, :store, :city_id, :phone)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer, html: {class: "form-horizontal"}) do |f| %>
<% if @customer.errors.any? %>
<div id="error_explanation">
	<h3><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h3>

	<ul>
		<% @customer.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-group">
	<div class="control-label col-sm-2">
		<%= f.label :owner %>
	</div>
	<div class="col-sm-4">
		<%= f.text_field :owner, placeholder: "mr. good man", class: "form-control" %>
	</div>
</div>
<div class="form-group">
	<div class="control-label col-sm-2">
		<%= f.label :store %><br>
	</div>
	<div class="col-sm-4">
		<%= f.text_field :store, placeholder: "abc garments", class: "form-control" %>
	</div>
</div>
<div class="form-group">
	<div class="control-label col-sm-2">
		<%= f.label :city %><br>
	</div>
	<div class="col-sm-4">
		<%= f.collection_select(:city_id, City.all, :id, :name, {prompt: "Select city"}, class: "form-control") %>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-2 control-label">
		<%= f.label :phone %><br>
	</div>
	<div class="col-sm-4">
		<%= f.text_field :phone, placeholder: "(333)555-9999", class: "form-control" %>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<%= f.submit "Submit", class: "btn btn-success" %>
	</div>
</div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

app/views/customers/index.html.erb
<h1 class="page-header">Customers</h1>

<div class-"form-inline" role="form">
	<%= form_tag(@customer, method: "get", ) do %>
	<div class="form-group">
		<div class="col-sm-4">
			<div class="input-group">
				<%= text_field_tag :search, params[:search], autofocus: true, placeholder: "store name", class: "form-control" %>
				<div class="input-group-btn">
					<button class="btn btn-default" type="submit">Search</button>
				</div>
			</div>
		</div>                          
	</div>                  
	<% end %>
	<%= link_to "Add customer", new_customer_path, class: "btn btn-success" %>
</div> 
					
<table class="table table-striped">
	<thead>
		<tr>
			<th>Owner</th>
			<th>Store</th>
			<th>City</th>
			<th>Phone</th>
			<th colspan="2"></th>
		</tr>
	</thead>

	<tbody>
		<% @customers.each do |customer| %>
		<tr>
			<td class="text-capitalize"><%= link_to customer.owner, customer %></td>
			<td class="text-capitalize"><%= link_to customer.store, customer %></td>
			<td class="text-capitalize"><%= customer.city.name %></td>
			<td><%= customer.phone %></td>
			<td><%= link_to 'Detail', customer_path(customer), class: "btn btn-primary btn-sm" %></td>
			<td><%= link_to 'Edit', edit_customer_path(customer), class: "btn btn-warning btn-sm" %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "Add customer", new_customer_path, class: "btn btn-success" %>

app/views/customers/new.html.erb
<h1 class="page-header">New Customer</h1>

<%= render 'form' %>

app/views/customers/show.html.erb
<h1 class="page-header text-primary">
	<%= "#{@customer.store} | #{@customer.city.name}" %>
</h1>
<h2 class="text-success pull-right">
	<%= "owner: 	#{@customer.owner} | phone: #{@customer.phone}" %>
</h2>
<p><%= link_to 'new order', new_order_path(customer_id: @customer), class: "btn btn-success" %></p>
<h3>
	List of orders:
</h3>

<% if @orders.blank? %>
<p>
	There is no order booked for this customer
</p>

<% else %>

<table class="table table-condensed">
	<tr>
		<th>Bill#</th>
		<th>Date</th>
		<th class="text-right">Total Amount</th>
		<th class="text-right">Discount %</th>
		<th class="text-right">Net Amount</th>
		<th>Action</th>
	</tr>
	<% @orders.each do |order| %>
	<tr>
		<td><%= order.bill_id %></td>
		<td><%= order.ordered_at.strftime("%Y-%b-%d") %></td>
		<td class="text-right"><%= number_with_delimiter(order.order_amount, delimiter: ",") %></td>
		<td class="text-right"><%= number_with_delimiter(order.discount, delimiter: ",") %></td>
		<td class="text-right"><%= number_with_delimiter(order.order_amount - (order.order_amount * order.discount / 100), delimiter: ",") %></td>
		<td><%= link_to 'detail', order_path(order), class: "btn btn-primary btn-sm"%></td>
	</tr>
	<% end %>
</table>
<% end %>