config/routes.rb
Rails.application.routes.draw do
  resources :cities

  get 'reports/index'

  get 'reports/sumbycustomer'

  get 'reports/sumbytime'

  get 'reports/sumbycity'

  devise_for :users
  resources :colours

  resources :order_lines do
    get 'additem', to: "orders#add_order_lines"
  end

  resources :orders do
    get 'compute', to: "orders#compute"
  end

  resources :customers

  resources :products

  root 'home#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  
  belongs_to :customer
  has_many :order_lines
  
  validates :bill_id, uniqueness: true, presence: true
  # validates :order_amount, inclusion: {in: 50..500000, message: "order must include items"}
  validates :discount, numericality: true
  
  accepts_nested_attributes_for :order_lines, reject_if: lambda {|a|a[:quantity].blank? },  allow_destroy: true
  
  # validates :order_amount
  # validates :attribute,  :acceptance => true,
  #                                 :confirmation => true,
  #                                 :exclusion => { :in => %w( mov avi ) },
  #                                 :inclusion => { :in => %w( mov avi ) },
  #                                 :format => { :with => /^[\w\d]+$/ },
  #                                 :length => { :minimum => 0, :maximum => 0, },
  #                                 :numericality => true,
  #                                 :presence => true,
  #                                 :uniqueness => true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order_line = OrderLine.new(order_id: params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new(customer_id: params[:customer_id], order_amount: 0)
  end

  # GET /orders/1/edit
  def edit
    @order.order_lines.build    
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  # def destroy
  #   @order.destroy
  #   respond_to do |format|
  #     format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  
  def compute
    total = 0
    @order = Order.find(params[:order_id])
    @order.order_lines.each do |order_line|
      order_line.update(price: Product.find(order_line.product_id).price)
      total = total + (order_line.quantity * order_line.price)
    end
    @order.update(order_amount: total)
    redirect_to edit_order_path(@order), notice: 'Order was successfully updated.'
  end

  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:customer_id, :bill_id, :discount, :ordered_at, :order_amount,  
    order_lines_attributes: [:id, :order_id,  :product_id, :colour_id, :quantity, :price, :_destroy])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_donotusetable.html.erb
<% if @order.order_lines.count >= 1 %>
<table class="table table-condensed">
	<tr>
		<th>code</th>
		<th>specification</th>
		<th>colour</th>
		<th>quantity</th>
	</tr>
	<% @order.order_lines.each do|order_line| %>
	<tr>
		<td><%= order_line.product_id %></td>
		<td><%= order_line.product_id %></td>
		<td><%= order_line.colour_id %></td>
		<td><%= order_line.quantity %></td>
	</tr>
	<% end %>
</table>
<% end %>

app/views/orders/_form.bak.html.erb
<div class="form-horizontal" role="form">
	<%= form_for(@order) do |f| %>
	<% if @order.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
		<ul>
			<% @order.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<%= f.hidden_field :customer_id %>
	<%= f.hidden_field :order_amount %>
	<div class="form-group">
		<div class="col-sm-2 form-label">
			<%= f.label 'Bill #' %>
		</div>
		<div class="col-sm-2">
			<%= f.text_field :bill_id, class: "form-control"%>
		</div>
		<div class="col-sm-2 form-label">
			<%= f.label 'Discount %' %>
		</div>
		<div class="col-sm-2">
			<%= f.number_field :discount, placeholder: 0.0, step: 0.5, min: 0.0, max: 99.0 , class: "form-control"%>
		</div>
	</div>
	<%= f.fields_for :order_lines do |olf| %>
	<%= olf.hidden_field :order_id %>
	<%= olf.label :product_id %>
	<%= olf.collection_select(:product_id, Product.all, :id, :code) %>
	<%= olf.label :colour_id %>
	<%= olf.collection_select(:colour_id, Colour.all, :id, :name) %>
	<%= olf.label :quantity %>
	<%= olf.number_field :quantity, placeholder: 1, min: 1, max: 10000, step: 1 %>
	<%= olf.label :price %>
	<%= olf.number_field :price, class: "form-control-static" %>
	<%#= olf.price %>
	<%= olf.check_box :_destroy %>
	<p><%#= link_to_add_fields "Add Question", f, :questions %></p>
	<% end %>
	<div class="form-group">
		<%#= link_to "add product", add_order_lines, class: "btn btn-default btn-sm"%>
	</div>
	<div class="pull-right">
		<p id="order_amount"></p>
	</div>
	<div class="actions">
		<%= f.submit 'Submit', class: "btn btn-default" %>
	</div>
	<% end %>
</div>

app/views/orders/_form.html copy.erb
<div class="form-horizontal" role="form">
	<%= form_for(@order) do |f| %>
	<% if @order.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
		<ul>
			<% @order.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<%= f.hidden_field :customer_id %>
	<%#= f.hidden_field :order_amount %>
	<div class="row">
		<div class="form-group">
			<div class="col-sm-2 form-label">
				<%= f.label 'Bill #' %>
			</div>
			<div class="col-sm-1">
				<%= f.text_field :bill_id, class: "form-control"%>
			</div>
			<div class="col-sm-2 form-label">
				<%= f.label "Discount %" %>
			</div>
			<div class="col-sm-1">
				<%= f.number_field :discount, value: 0.0, step: 0.5, min: 0.0, max: 99.0 , class: "form-control"%>
			</div>
			<div class="col-sm-2 form-label">
				<%= f.label "Order amount: "%>
				<span class="badge"><%= @order.order_amount %></span>
			</div>
		</div>
	</div>
	<%= f.fields_for :order_lines do |olf| %>
	<div class="form-group">
		<div class="col-sm-12">
			<%= olf.hidden_field :order_id %>
			<%= olf.label :product_id %>
			<%= olf.collection_select(:product_id, Product.all, :id, :code) %>
			<%= olf.label :colour_id %>
			<%= olf.collection_select(:colour_id, Colour.all, :id, :name) %>
			<%= olf.label :quantity %>
			<%= olf.number_field :quantity, min: 1, max: 10000, step: 1 %>
			<%= olf.label "Unit price" %>
			<%= olf.number_field :price, min: 100, max: 10000, step: 1 %>
			<%= olf.check_box :_destroy %>
		</div>
	</div>
	<% end %>
	<div class="actions">
		<%= f.submit "Submit", class: "btn btn-default" %>
		<%= link_to "Compute", order_compute_path(@order.id), class: "btn btn-primary"%>
	</div>
	<% end %>
</div>

app/views/orders/_form.html.erb
<div class="form-inline" role="form">
	<%= form_for(@order) do |f| %>
	<% if @order.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
		<ul>
			<% @order.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<%= f.hidden_field :customer_id %>
	<div class="form-group">
		<%= f.label "Bill #" %>
		<%= f.text_field :bill_id, class: "form-control"%>
	</div>
	<div class="form-group">
		<%= f.label "Order date" %>
		<%= f.date_field :ordered_at, placeholder: "yyyy-mm-dd", class: "form-control"%>
	</div>
	<div class="form-group">
		<%= f.label "Discount %" %>
		<%= f.number_field :discount, step: 0.5, min: 0.0, max: 99.0 , class: "form-control"%>
	</div>
	<div class="form-group">
			<%= f.submit "Submit", class: "btn btn-success" %>
	</div>
	<% end %>
</div>

app/views/orders/_order_lines.html.erb
<%= f.fields_for :order_lines do |olf| %>
	<%= olf.hidden_field :order_id %>
	<%= olf.label :product_id %>
	<%= olf.collection_select(:product_id, Product.all, :id, :code) %>
	<%= olf.label :colour_id %>
	<%= olf.collection_select(:colour_id, Colour.all, :id, :name) %>
	<%= olf.label :quantity %>
	<%= olf.number_field :quantity, in: 1..10000, step: 1 %>
	<%= olf.check_box :_destroy %>
	<p><%#= link_to_add_fields "Add Question", f, :questions %></p>
<% end %>

app/views/orders/edit.html.erb
<h1 class="page-header text-primary">
	<%= link_to "#{@order.customer.store} | #{@order.customer.city.name}", customer_path(@order.customer_id) %>
</h1>

<%= render 'form' %>

app/views/orders/index.html.erb
<h1 class="page-header">Orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Order amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer %></td>
        <td><%= order.order_amount %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1 class="page-header text-primary">
	<%= link_to "#{@order.customer.store} | #{@order.customer.city.name}", customer_path(@order.customer) %>
</h1>
<%= render 'form' %>

app/views/orders/show.html.erb
<h1 class="page-header text-primary">
	<%= link_to "#{@order.customer.store} | #{@order.customer.city.name}", customer_path(@order.customer_id) %>
</h1>

<h3 class="text-success pull-right">
	order # <%= @order.id %>, overall discount: <%= @order.discount%>%
</h3>

<% if @order.order_lines.count >= 1%>
<table class="table table-condensed">
	<tr>
		<th>Product</th>
		<th>Colour</th>
		<th class="hidden-xs">Specification</th>
		<th>Quantity</th>
		<th>Unit Price</th>
		<th>Total Price</th>
		<th>Action</th>
	</tr>
	<% order_total = 0 %>
	<% @order.order_lines.each do |order_line| %>		
	<tr>
		<td><%= order_line.product.code %></td>
		<td><%= order_line.colour.name %></td>
		<td class="hidden-xs"><%= order_line.product.specification %></td>
		<td><%= order_line.quantity %></td>
		<td><%= order_line.price %></td>
		<td><%= order_line.price * order_line.quantity %></td>
		<td><%= link_to "edit", edit_order_line_path(order_line), class: "btn btn-warning btn-sm" %>
			<%= link_to "delete", order_line_path(order_line), method: :delete, class: "btn btn-danger btn-sm" %>
		</td>
	</tr>
	<% order_total = order_total + (order_line.price * order_line.quantity) %>
	<% end %>
	<tr>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td><strong>Total</strong></td>
		<td class="text-info">
			<strong><%= order_total %></strong>
		</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>Discount</td>
		<td class="text-info">
			(<%= order_total * @order.discount / 100 %>)
		</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td><strong>Net Amount</strong></td>
		<td class="text-info">
			<strong><%= order_total - (order_total * @order.discount / 100) %></strong>
		</td>
		<td></td>
	</tr>
</table>
<% end %>
	<%= form_for(@order_line, html: {class: "form-inline"}) do |f| %>
	<%= f.hidden_field :order_id %>
	<% if @order_line.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@order_line.errors.count, "error") %> prohibited this order_line from being saved:</h2>
		<ul>
			<% @order_line.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="form-group">
		<%= f.label :product_id %>
		<%= f.collection_select(:product_id, Product.all, :id, :code, {prompt: false}, class: "form-control") %>
	</div>
	<div class="form-group">
		<%= f.label :colour_id %>
		<%= f.collection_select(:colour_id, Colour.all.order("name"), :id, :name, {prompt: "Select colour"}, class: "form-control") %>
	</div>
	<div class="form-group">
		<%= f.label :quantity %>
		<%= f.number_field :quantity, value: 1, min: 1, max: 100000, step: 1, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.submit "Add product", class: "btn btn-success btn-sm" %>
	</div>
	<% end %>
	<hr>
	<%= link_to 'Edit', edit_order_path(@order), class: "btn btn-warning" %> 
	<%= link_to 'Back', customer_path(@order.customer_id), class: "btn btn-primary" %>