config/routes.rb
Rails.application.routes.draw do
  resources :cities

  get 'reports/index'

  get 'reports/sumbycustomer'

  get 'reports/sumbytime'

  get 'reports/sumbycity'

  devise_for :users
  resources :colours

  resources :order_lines do
    get 'additem', to: "orders#add_order_lines"
  end

  resources :orders do
    get 'compute', to: "orders#compute"
  end

  resources :customers

  resources :products

  root 'home#index'

end

app/models/colour.rb
class Colour < ActiveRecord::Base
  has_many :order_lines
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  
  before_save {|colour|colour.name = colour.name.downcase}
  
  def self.search(search)
    where("name like lower(?)", "%#{search}%")
  end
  
end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
  before_action :set_colour, only: [:show, :edit, :update, :destroy]

  # GET /colours
  # GET /colours.json
  def index
    if params[:search]
      @colours = Colour.search(params[:search])
    else
      @colours = Colour.all.order("name")
    end
  end

  # GET /colours/1
  # GET /colours/1.json
  def show
  end

  # GET /colours/new
  def new
    @colour = Colour.new
  end

  # GET /colours/1/edit
  def edit
  end

  # POST /colours
  # POST /colours.json
  def create
    @colour = Colour.new(colour_params)

    respond_to do |format|
      if @colour.save
        format.html { redirect_to @colour, notice: 'Colour was successfully created.' }
        format.json { render :show, status: :created, location: @colour }
      else
        format.html { render :new }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colours/1
  # PATCH/PUT /colours/1.json
  def update
    respond_to do |format|
      if @colour.update(colour_params)
        format.html { redirect_to @colour, notice: 'Colour was successfully updated.' }
        format.json { render :show, status: :ok, location: @colour }
      else
        format.html { render :edit }
        format.json { render json: @colour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colours/1
  # DELETE /colours/1.json
  # def destroy
  #   @colour.destroy
  #   respond_to do |format|
  #     format.html { redirect_to colours_url, notice: 'Colour was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colour
      @colour = Colour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colour_params
      params.require(:colour).permit(:name)
    end
end

app/helpers/colours_helper.rb
module ColoursHelper
end

app/views/colours/_form.html.erb
<div>
<%= form_for(@colour, html: {class: "form-horizontal"}) do |f| %>
  <% if @colour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@colour.errors.count, "error") %> prohibited this colour from being saved:</h2>

      <ul>
      <% @colour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
		<div class="col-sm-2 control-label">
    <%= f.label :name %><br>
		</div>
		<div class="col-sm-2">
    <%= f.text_field :name, class: "form-control" %>
		</div>
  </div>
  <div class="form-group">
		<div class="col-sm-offset-2 col-sm-2">
    <%= f.submit "Submit", class: "btn btn-success" %>
		</div>
  </div>
<% end %>
</div>

app/views/colours/edit.html.erb
<h1>Editing Colour</h1>

<%= render 'form' %>

<%= link_to 'Show', @colour %> |
<%= link_to 'Back', colours_path %>

app/views/colours/index.html.erb
<h1 class="page-header">Colours</h1>
<div class-"form-inline" role="form">
	<%= form_tag(@colour, method: "get", ) do %>
	<div class="form-group">
		<div class="col-sm-4">
			<div class="input-group">
				<%= text_field_tag :search, params[:search], autofocus: true, placeholder: "colour", class: "form-control" %>
				<div class="input-group-btn">
					<button class="btn btn-default" type="submit">Search</button>
				</div>
			</div>
		</div>                          
	</div>                  
	<% end %>
	<%= link_to "Add colour", new_colour_path, class: "btn btn-success" %>
</div> 

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @colours.each do |colour| %>
		<tr>
			<td><%= colour.name.capitalize %></td>
			<td><%= link_to 'Edit', edit_colour_path(colour) , class: "btn btn-warning btn-sm"%></td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Add colour", new_colour_path, class: "btn btn-success" %>

app/views/colours/new.html.erb
<h1 class="page-header">New Colour</h1>

<%= render 'form' %>

<%#= link_to 'Back', colours_path, class: "btn btn-primary" %>

app/views/colours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @colour.name %>
</p>

<%= link_to 'Edit', edit_colour_path(@colour) %> |
<%= link_to 'Back', colours_path %>