config/routes.rb
Rails.application.routes.draw do
  resources :cities

  get 'reports/index'

  get 'reports/sumbycustomer'

  get 'reports/sumbytime'

  get 'reports/sumbycity'

  devise_for :users
  resources :colours

  resources :order_lines do
    get 'additem', to: "orders#add_order_lines"
  end

  resources :orders do
    get 'compute', to: "orders#compute"
  end

  resources :customers

  resources :products

  root 'home#index'

end

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
<hr>
<ul class="nav nav-pills">
	<li><%= link_to 'Home', root_path %></li>
	<li><%= link_to 'Products', products_path %></li>
	<li><%= link_to 'Colours', colours_path %></li>
	<li><%= link_to 'Customers', customers_path %></li>
	<li><%= link_to 'Reports', reports_index_path %></li>
	<li class="pull-right"><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm" %></li>
</ul>
<hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>T2</title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
		<% if notice %>
		<p class="alert alert-info"><%= notice %></p>
		<% end %>
		<% if alert %>
		<p class="alert alert-danger alert-dismisible"><%= alert %></p>
		<% end %>
			<%= yield %>
		<div class= "footer">
			<%= render :partial => 'layouts/footer' %>
		</div>
	</div>
</body>
</html>